kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ .Values.app }}
  labels:
    app: gpnsm-front
    label: gpnsm
    service: {{ .Values.app }}
spec:
  resources:
    limits:
      cpu: '2'
      memory: '3Gi'
    requests:
      cpu: '100m'
      memory: '100Mi'
  nodeSelector: null
  strategy:
    dockerStrategy:
      dockerfilePath: {{ .Values.image.source.dockerfilePath }}
      env:
        - name: APP
          value: {{ .Values.app }}
      {{- range $key, $val := .Values.env.build }}
        - name: {{ $key }}
          value: {{ $val | quote }}
      {{- end }}
      pullSecret:
        name: nexus-docker
    type: Docker
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 3
  runPolicy: SerialLatestOnly
  source:
    type: Git
    git:
      uri: git@git.grotem.com:GPNLubricants/Frontend.git
      ref: {{ .Values.image.source.ref }}
    sourceSecret:
      name: grotem-git-openshift-builder
  output:
    pushSecret:
      name: nexus-gpnsm
    to:
      kind: DockerImage
      name: 'gpnsm.nexus.okd.local:5000/{{ .Values.image.source.ref }}/{{ .Values.app }}:latest'
  triggers: []