apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: gpnsm-front
    label: gpnsm
    service: {{ .Values.app }}
  name: {{ .Values.app }}
spec:
  lookupPolicy:
    local: false