kind: Route
apiVersion: route.openshift.io/v1
metadata:
  {{- if eq .Values.route.acme "true" }}
  annotations:
    kubernetes.io/tls-acme: "true"
  {{ end }}
  name: {{ .Values.app }}
  labels:
    app: gpnsm-front
    label: gpnsm
    service: {{ .Values.app }}
spec:
  host: {{ .Values.route.host }}
  path: /
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: {{ .Values.app }}
    weight: 100
  wildcardPolicy: None