kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.app }}
  labels:
    app: gpnsm-front
    label: gpnsm
    service: {{ .Values.app }}
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: metrics
      port: 9113
      protocol: TCP
      targetPort: 9113
  selector:
      deploymentconfig: {{ .Values.app }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
